// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLNetOnRaspberryML.Model
{
    public class ModelInput
    {
        [ColumnName("Time"), LoadColumn(0)]
        public string Time { get; set; }


        [ColumnName("DayOfWeek"), LoadColumn(1)]
        public float DayOfWeek { get; set; }


        [ColumnName("DidTeamWin"), LoadColumn(2)]
        public float DidTeamWin { get; set; }


        [ColumnName("NumberOfBolts"), LoadColumn(3)]
        public float NumberOfBolts { get; set; }


        [ColumnName("AvgTime"), LoadColumn(4)]
        public string AvgTime { get; set; }


        [ColumnName("TimeDif"), LoadColumn(5)]
        public float TimeDif { get; set; }


        [ColumnName("Min"), LoadColumn(6)]
        public float Min { get; set; }


        [ColumnName("Max"), LoadColumn(7)]
        public float Max { get; set; }


    }
}
