// This file was auto-generated by ML.NET Model Builder. 

using System;
using MLNetOnRaspberryML.Model;

namespace MLNetOnRaspberryML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Time = @"08:00",
                DayOfWeek = 1F,
                DidTeamWin = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual NumberOfBolts with predicted NumberOfBolts from sample data...\n\n");
            Console.WriteLine($"Time: {sampleData.Time}");
            Console.WriteLine($"DayOfWeek: {sampleData.DayOfWeek}");
            Console.WriteLine($"DidTeamWin: {sampleData.DidTeamWin}");
            Console.WriteLine($"\n\nPredicted NumberOfBolts: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
